### ISSUE TITLE
Что это?

### ISSUE THREAD

**Issue by maximLM** [BigPolandBro/BigInteger#14]
https://github.com/BigPolandBro/BigInteger/blob/526ef027d62157f0f2d4a542ed70ea5378ac595b/BigInteger.cpp#L83-L94
В этом методе излишни исключения, ты либо
1) бросай исключения и не лови их у себя
2) Не бросай исключения
Я бы сделал 1 вариант, но добавил бы метод типа FitsIntoInt()
Вообще я бы убрал неявное преобразование в инт (слишком опасно) инаписал бы явный метод IntValue()

**Comment by BigPolandBro** [comment]
Я же добавил ключевое слово explicit, поэтому запретил делать это неявно
